### ISSUE TITLE
Beta65s Update Procedure?

### ISSUE THREAD

**Issue by Skipper-is** [dainiauskas/fpv#1]
What is your process for updating the 65s? I've just found that mine has erased everything, so I'd be interested to hear your process?

**Comment by dainiauskas** [comment]
Connect to Betaflight, go to section CLI, copy all from *.txt and paste into command line, press ENTER then type save and ENTER button. Then your flight controller restarted with new configuration.

**Comment by dainiauskas** [comment]
Closed
